Repository JuliaAnimators/Javis.jl, pull requests merged in 2020-08, with the labels that each got.

#15 Simple morph between paths. SORRY FOR THE WEIRD COLORS
  src/Javis.jl
  src/morphs.jl
  test/animations.jl
  test/refs/star2circle5.png
Labels: BRIGHT COLORS

#18 [WIP] Grid Lines Animation
  src/Javis.jl
  src/backgrounds.jl
  test/animations.jl
  test/refs/grid_drawing_bl.png
  test/refs/grid_drawing_br.png
  test/refs/grid_drawing_tl.png
  test/refs/grid_drawing_tr.png
Labels: documentation, enhancement

#71 Auto export of Luxor functions
  src/Javis.jl
  test/runtests.jl
Labels: documentation, enhancement

#28 Fixing documentation for latex
  src/Javis.jl
Labels: documentation

#72 Subactions
  src/Javis.jl
  src/backgrounds.jl
  src/luxor_overrides.jl
  src/morphs.jl
  src/subaction_animations.jl
  src/svg2luxor.jl
  test/animations.jl
  test/refs/circle_angle.png
  test/refs/circlerSquare07opacity.png
  test/refs/circlerSquare25opacity.png
  test/refs/circlerSquare42opacity.png
  test/refs/dancing_circles_16.png
  test/refs/dancing_circles_16_rot_trans.png
  test/refs/grid_drawing_bl.png
  test/refs/grid_drawing_br.png
  test/refs/grid_drawing_tl.png
  test/refs/grid_drawing_tr.png
  test/refs/nicholas15.png
  test/refs/nicholas25.png
  test/refs/nicholas35.png
  test/refs/star2circle15.png
  test/refs/star2circle5.png
Labels: enhancement

#50 Project Tutorials and General Docs Improvements
  README.md
  docs/make.jl
  docs/src/contributing.md
  docs/src/index.md
  docs/src/tutorials/assets/blank.gif
  docs/src/tutorials/assets/eeg.gif
  docs/src/tutorials/assets/eeg_colors.gif
  docs/src/tutorials/assets/electrodes.gif
  docs/src/tutorials/assets/head.gif
  docs/src/tutorials/assets/head_gridlines.gif
  docs/src/tutorials/tutorial_1.md
  docs/src/tutorials/tutorial_2.md
  docs/src/tutorials/tutorial_3.md
Labels: documentation, enhancement

#81 First draft of the mission statement
  docs/make.jl
  docs/src/mission.md
Labels: documentation

#86 Tutorial on Actions
  docs/src/tutorials/tutorial_2.md
Labels: documentation

#84 Tutorial #4: The creation of Jarvis
  docs/make.jl
  docs/src/tutorials/assets/jarvis.gif
  docs/src/tutorials/assets/jarvis_nose.gif
  docs/src/tutorials/tutorial_4.md
Labels: documentation

#90 Sudomaze tutorial
  README.md
  assets/eeg.gif
  assets/jarvis.gif
  docs/src/tutorials/assets/background.gif
  docs/src/tutorials/assets/circle.gif
  docs/src/tutorials/assets/connect_two_points.gif
  docs/src/tutorials/assets/dancing_circles.gif
  docs/src/tutorials/assets/dotted_points.gif
  docs/src/tutorials/assets/dynamic_rotation.gif
  docs/src/tutorials/assets/multiple_circles.gif
  docs/src/tutorials/assets/rotation.gif
  docs/src/tutorials/tutorial_1.md
  docs/src/tutorials/tutorial_2.md
Labels: documentation

#94 LaTeX Tutorial
  docs/src/tutorials/assets/boring_matrix.gif
  docs/src/tutorials/assets/flaming_matrix.gif
  docs/src/tutorials/tutorial_3.md
Labels: documentation, enhancement

#104 Hotfix for latex docstring
  src/Javis.jl
Labels: documentation

#112 Adding basic functionality for generating mp4 file
  Project.toml
  src/Javis.jl
  test/Project.toml
  test/animations.jl
  test/runtests.jl
Labels: enhancement

#115 General Improvements for Documentation
  README.md
  docs/src/index.md
  docs/src/tutorials/tutorial_1.md
  docs/src/tutorials/tutorial_2.md
  docs/src/tutorials/tutorial_3.md
  docs/src/tutorials/tutorial_4.md
Labels: bug, documentation

#124 Applied JuliaFormatter to all of Javis.jl files
  .github/workflows/format_check.yml
  CHANGELOG.md
  docs/make.jl
  src/backgrounds.jl
  src/luxor_overrides.jl
  src/morphs.jl
  src/subaction_animations.jl
  src/svg2luxor.jl
  src/util.jl
  test/animations.jl
  test/svg.jl
  test/unit.jl
Labels: documentation, enhancement, question
