Repository JuliaAnimators/Javis.jl, pull requests merged in 2020-09, with the labels that each got.

#125 Using Animations.jl
  .gitignore
  CHANGELOG.md
  Project.toml
  TODO.md
  src/Javis.jl
  src/luxor_overrides.jl
  src/subaction_animations.jl
  src/util.jl
  test/Project.toml
  test/animations.jl
  test/refs/anim_circle020.png
  test/refs/anim_circle075.png
  test/refs/anim_circle142.png
  test/refs/animations_all_05.png
  test/refs/animations_all_125.png
  test/refs/animations_all_145.png
  test/refs/animations_all_25.png
  test/refs/animations_all_65.png
  test/refs/circleSquare07opacity.png
  test/refs/circleSquare25opacity.png
  test/refs/circleSquare42opacity.png
  test/refs/rotate_center25.png
  test/refs/rotate_center45.png
  test/runtests.jl
  test/unit.jl
Labels: enhancement

#159 Updated testing guidelines
  .JuliaFormatter.toml
  CHANGELOG.md
  contributing.md
  docs/src/contributing.md
Labels: documentation, enhancement

#160 Tutorial 5 on Scaling
  docs/make.jl
  docs/src/tutorials/assets/atomic.gif
  docs/src/tutorials/assets/blank_atom_scaling.gif
  docs/src/tutorials/assets/min_atomic_info.gif
  docs/src/tutorials/tutorial_5.md
Labels: documentation

#165 Added tutorial 5 to Tutorial Index
  docs/src/tutorials.md
Labels: documentation

#154 Wik feature morphing v2
  CHANGELOG.md
  TODO.md
  src/morphs.jl
  test/animations.jl
  test/refs/star2circle_fill15.png
  test/refs/star2circle_fill5.png
Labels: enhancement

#119 [WIP] Live Preview
  .github/workflows/ci.yml
  Project.toml
  src/Javis.jl
  src/javis_viewer.jl
  src/svg2luxor.jl
  test/Project.toml
  test/runtests.jl
  test/viewer.jl
Labels: enhancement

#182 Wik documentation push preview
  docs/make.jl
Labels: enhancement

#195 Remove any files stored in test/images
  test/unit.jl
Labels: bug, enhancement

#200 Update for Tutorial 5
  docs/src/tutorials/assets/atomic.gif
  docs/src/tutorials/assets/min_atomic_info.gif
  docs/src/tutorials/tutorial_5.md
Labels: documentation

#197 Animation showcase for Javis
  README.md
  assets/atomic.gif
  assets/dancing_circles.gif
  assets/eeg.gif
  assets/jarvis.gif
  assets/loading.gif
  assets/matrix.gif
  examples/gifs/follow_bezier_path.gif
Labels: documentation, enhancement, question

#203 Added Examples Page
  docs/make.jl
  docs/src/assets/follow_bezier_path.gif
  docs/src/examples.md
Labels: documentation
